### ISSUE TITLE
How can I make instruction duplication with this work?

### ISSUE THREAD

**Issue by xiaofengwo** [DependableSystemsLab/Trident#5]
I found this code has the ability to make instruction duplication and duplication check.
But when I tried this, I found there may be some check functions used in the DuplicationCheck pass are not defined.
Is it defined in the file "sync_check.ll"? And where should I find it ?

Besides, how can I generate the "select_set_file" needed by the DuplicationCheck pass? 
Thanks.

**Comment by zujia** [comment]
> I found this code has the ability to make instruction duplication and duplication check.
> But when I tried this, I found there may be some check functions used in the DuplicationCheck pass are not defined.
> Is it defined in the file "sync_check.ll"? And where should I find it ?
> 
> Besides, how can I generate the "select_set_file" needed by the DuplicationCheck pass?
> Thanks.

I have encountered the same problem as you. Have you solved this problem?

**Comment by cclinus** [comment]
@zujia 
Can you please check this LLVM pass in the repo?
https://github.com/DependableSystemsLab/Trident/tree/master/llvm-2.9/lib/Transforms/RecovProtectInlineFuncCheck

As I recall, this is an optimized version of DMR which inlines the checker function in IR instead of having an external function call. Please give it a try.

"select_set_file" is a text file that specifies which instructions need to be duplicated. So list all the LLVM IR instruction index in the file, and execute the duplication pass, it will duplicate the instructions specified.
